### PR TITLE
Bug fix #945 - Pause in queue with concurrency doesn't pause

### LINKED ISSUE #945: Pause in queue with concurrency doesn't pause
Hi,

The queue will continue to process tasks when these conditions are met:
 - using a queue with a concurrency > 1
 - the task pauses the queue
 - the task is long running and the callback is not called before adding more items to the queue

I will submit a pull request to resolve this.

Adam.

### PR DESCRIPTION
**Pull request by adam-26**
Refer to issue #945

### CODE REVIEW

File: lib/async.js [hunk 1]
```diff
@@ -931,6 +931,10 @@
             process: function () {
                 if (!q.paused && workers < q.concurrency && q.tasks.length) {
                     while(workers < q.concurrency && q.tasks.length){
```
Comment (megawac) [inline lib/async.js]: Can you change this to

```diff
- if (!q.paused && workers < q.concurrency && q.tasks.length) { 
- while(workers < q.concurrency && q.tasks.length){ 
+ while (!q.paused && workers < q.concurrency && q.tasks.length) {
```

**Comment by adam-26** [comment]
Done
